---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: yages
  name: yages
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yages
  template:
    metadata:
      labels:
        app: yages
    spec:
      containers:
      - image: quay.io/mhausenblas/yages:0.1.0
        name: grpcsrv
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: yages
  name: yages
spec:
  type: ClusterIP
  ports:
  - name: grpc
    port: 9000
    protocol: TCP
  selector:
    app: yages
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: grpc-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 443
      name: grpc
      protocol: GRPC
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grpc-vs
spec:
  hosts:
  - "*"
  gateways:
  - grpc-gateway
  http:
    - match:
        - port: 443
      route:
        - destination:
            host: yages
            port:
              number: 9000
 
